[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B"] # Standard set of rules
ignore = ["B008"] # Don't complain about function calls in default arguments

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true